name: "Merge pull requests (automerge-action)"
description: "Automatically merge pull requests that are ready"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "git-pull-request"
  color: "blue"
